[package]
name = "rg_test"
version = "0.1.0"
# build = "shaders/build.rs"
authors = ["fkaa"]

[dependencies]
rg = { path = ".." }
winapi = { version = "0.3", features = ["everything"] }
glutin = "0.18"
gl = "*"